#include "bsp_elog.h"

void bsp_elog_init(void)
{
	elog_init();

	elog_set_fmt(ELOG_LVL_ASSERT, ELOG_FMT_ALL);
	elog_set_fmt(ELOG_LVL_ERROR, (ELOG_FMT_LVL|ELOG_FMT_TAG|ELOG_FMT_TIME));
	elog_set_fmt(ELOG_LVL_WARN, (ELOG_FMT_LVL|ELOG_FMT_TAG|ELOG_FMT_TIME));
	elog_set_fmt(ELOG_LVL_INFO, (ELOG_FMT_LVL|ELOG_FMT_TAG|ELOG_FMT_TIME));
	elog_set_fmt(ELOG_LVL_DEBUG, (ELOG_FMT_LVL|ELOG_FMT_TAG|ELOG_FMT_TIME|ELOG_FMT_DIR|ELOG_FMT_LINE));
	elog_set_fmt(ELOG_LVL_VERBOSE, (ELOG_FMT_LVL|ELOG_FMT_TAG|ELOG_FMT_TIME|ELOG_FMT_DIR|ELOG_FMT_LINE));

	elog_start();
}


